### ISSUE TITLE
Probleme beim Start

### ISSUE THREAD

**Issue by bytec77** [carp3-noctem/neeo-driver-enigma2#3]
Nach dem Start bekomme ich folgende Fehlermeldung. Was kann das sein? 

`> neeo-driver-enigma2@0.2.2 start /home/pi/node_modules/neeo-driver-enigma2
> neeo-sdk start

NEEO SDK Example "Enigma2" adapter
---------------------------------------------
No Brain address configured, attempting to discover one...
- Brain discovered: NEEO Living Room
- Start server
ERROR! TypeError: device.build is not a function
    at buildAndRegisterDevice (/home/pi/node_modules/neeo-driver-enigma2/node_modules/neeo-sdk/lib/device/index.js:102:30)
    at conf.devices.map (/home/pi/node_modules/neeo-driver-enigma2/node_modules/neeo-sdk/lib/device/index.js:94:14)
    at Array.map (<anonymous>)
    at BluePromise (/home/pi/node_modules/neeo-driver-enigma2/node_modules/neeo-sdk/lib/device/index.js:93:34)
    at Promise._execute (/home/pi/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/home/pi/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/pi/node_modules/bluebird/js/release/promise.js:79:10)
    at buildDevicesDatabase (/home/pi/node_modules/neeo-driver-enigma2/node_modules/neeo-sdk/lib/device/index.js:92:10)
    at validateBrainVersion.then (/home/pi/node_modules/neeo-driver-enigma2/node_modules/neeo-sdk/lib/device/index.js:53:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! neeo-driver-enigma2@0.2.2 start: `neeo-sdk start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the neeo-driver-enigma2@0.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-11-08T21_57_07_644Z-debug.log`

**Comment by carp3-noctem** [comment]
@bytec77 Hab es gefixt. Sorry das es so lange gedauert hat. Ich hatte keine Zeit bis heute. Mit der aktuellen Version sollte es wieder laufen.
